version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    container_name: mysql_db_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root' 
      MYSQL_DATABASE: 'nex_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password' 
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: