name: Sincronizar Pastas Frontend e Backend

on:
  push:
    branches:
      - main 

jobs:
  sync-folders:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar o código do Monorepo
        uses: actions/checkout@v3

      - name: 2. (Debug) Listar arquivos na pasta 'frontend'
        run: |
          echo "Verificando o conteúdo da pasta 'frontend':"
          ls -la frontend

      - name: 3. Enviar pasta 'frontend' para o repositório de frontend
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DESTINO_TOKEN}}
          repository-name: BedeJesus/teste-nex-frontend
          branch: master 
          folder: frontend 
          clean: true
          force: true

      - name: 4. (Debug) Listar arquivos na pasta 'backend'
        run: |
          echo "Verificando o conteúdo da pasta 'backend':"
          ls -la backend

      - name: 5. Enviar pasta 'backend' para o repositório de backend
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DESTINO_TOKEN}}
          repository-name: BedeJesus/teste-nex-backend 
          branch: main 
          folder: backend 
          clean: true 
          force: true 